name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        registry: registry.txt.isaacbs.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tinywebserver:dev
    - name: Docker tag images
      run: docker tag tinywebserver:dev registry.txt.isaacbs.com/tinywebserver:dev
    - name: Push Gateway image
      run: docker push registry.txt.isaacbs.com/tinywebserver:dev




